package.json

Rename from q-template-application to q-templates-application. Provides a namespace "q-templates" for future templates.

Rename module to q-templates-application

---

index.js
package-lock.json
package.json

- Added new flow for v1.0.0
- Bumped version to v1.0.0

Release candidate v1.0.0

---

index.js

This PR includes the template v1.2.0 which reflects our pre-pilot state.
Test passes.
Manual testing passes.
Lint passes.

Template v1.2.0

---

index.js

* Make all contact information consistent
* content now in a partial

Update contact information

---

index.js

Add `contact.njk` partial to `'you-cannot-get-compensation'` section

Add extra contact information

---

index.js

This PR updates the declaration page on the VOSSA journey
Test passes
Lint passes
Manual Test passes.

Updated the declaration on the vossa journey

---

index.js

This PR updates the template to v1.2.3.
This version has an update to the label on the treatment page.

Update to v1.2.3 Add treatment content update

---

package-lock.json
package.json

Bump to latest version. All tests passing.

Bump q-template-validator to 1.1.1

---

index.js
package-lock.json
package.json

This PR updates the flow for 'other medical treatment'.
This PR also includes a bump to version 1.3.0
Test passes
Lint passes
Manual testing passes

Other medical treatment

---

index.js

Add `errorMessage` property to the incident type schema

Add incident type error message

---

index.js
package-lock.json
package.json

Increase the maxlength from 500 to 1000

Increase char limit on `affect on daily life` schema

---

index.js
package-lock.json
package.json

This PR includes the new triage flow, and the new CYA structure.
It also includes a bump to v1.4.0
Manually tested
Lint pass
Test pass

Release candidate v1.4.0

---

index.js
package-lock.json
package.json

Update order of CYA summary structure.
Update template to v2.0.0

Update shape of CYA summary structure

---

index.js
package-lock.json
package.json

Move the title property in each schema to be in a consistent place.

Make title placement consistent

---

index.js
package-lock.json
package.json

Updates the template to align with questionnaireDocumentVersion 2.0.0 (qdv2) format.
Bumps q-validator to 2.0.0 to be able to validate the qdv2 format.
All automated tests passing.
Proposing a major (3.0.0) module bump too.

Add schema prop to sections

---

index.js
package-lock.json
package.json

Remove `span` tags and unwanted line breaks from the schema

Remove unwanted span tags and line breaks

---

index.js

Add contextualised personal injury pages

Contextualise physical injury questions

---

index.js

Add contextualised victim details

Add contextualised options for victim details screens

---

index.js
package-lock.json
package.json

Fixes the bug where the hint test is not displaying on the page for this schema.

Move `description` property to key of `properties` property

---

index.js
package-lock.json
package.json

The PR changes all boolean types in the template to the `oneOf` style of schema
Unit tests pass
Manual tests pass
Lint pass

Update boolean schemas

---

src/template.js

minor content updates + minor accessibility changes

Minor content + accessibility changes

---

package-lock.json
src/template.js

Add l10n block and contextualised titles to themes.

add l10n block to themes

---

src/lib/deleteKeys.js
src/lib/deleteKeys.test.js
src/template.js

contextualised template ids used in place of body content.
proposed version bump 6.0.0? breaking changes due to task change from array to map?

adding notification contextualisation support

---

src/lib/resource/sections/applicant-affect-on-daily-life-dmi.js
src/lib/resource/sections/applicant-are-you-claiming-for-physical-injuries.js
src/lib/resource/sections/applicant-dentist-visited.js
src/lib/resource/sections/applicant-enter-your-address.js
src/lib/resource/sections/applicant-have-you-been-known-by-any-other-names.js
src/lib/resource/sections/applicant-have-you-seen-a-gp.js
src/lib/resource/sections/applicant-infections.js
src/lib/resource/sections/applicant-medical-help.js
src/lib/resource/sections/applicant-pregnancy-loss.js
src/lib/resource/sections/applicant-pregnancy.js

Add contextualised summary titles

Add contextualised summaries

---

src/lib/resource/sections/applicant-enter-your-name.js

Add missing summary context

---

src/lib/resource/sections/applicant-affect-duration.js
src/lib/resource/sections/applicant-describe-incident.js
src/lib/resource/sections/applicant-enter-your-address.js
src/lib/resource/sections/applicant-have-you-applied-to-us-before.js
src/lib/resource/sections/mainapplicant-enter-your-address.js
src/lib/resource/sections/mainapplicant-enter-your-name.js

adding in correct theme summary titles

theme title content updates

---

src/lib/resource/sections/applicant-are-you-18-or-over.js

fix for someone else over 18 transition

someone else over 18 transition fix

---

src/lib/resource/sections/applicant-do-you-have-disabling-mental-injury.js

Update DMI description to be more inclusive to cater for more than one user group/context

Update DMI description

---

src/lib/resource/sections/applicant-future-work.js
src/lib/resource/sections/applicant-work-details-option.js

Update content on the impact of injury sections

Update impact of injury sections

---

src/lib/resource/sections/rep-address.js
src/lib/resource/sections/rep-reference-number.js

- summary fix for rep-reference
- error message fixes for rep-address

Feature/third party/content fixes

---

package-lock.json
package.json
src/lib/resource/sections/applicant-applied-for-other-compensation-briefly-explain-why-not.js
src/lib/resource/sections/applicant-have-you-applied-for-or-received-any-other-compensation.js
src/lib/resource/sections/applicant-have-you-applied-to-us-before.js
src/lib/resource/sections/context-compensation.js
src/lib/resource/sections/context-rep-details.js
src/lib/resource/sections/mainapplicant-care-order.js
src/lib/resource/sections/mainapplicant-parent.js
src/lib/resource/sections/rep-address.js
src/lib/resource/sections/rep-claims-management-reg.js
src/lib/resource/sections/rep-confirmation-method.js
src/lib/resource/sections/rep-email-address.js
src/lib/resource/sections/rep-name.js
src/lib/resource/sections/rep-organisation-name.js
src/lib/resource/sections/rep-reference-number.js
src/lib/resource/sections/rep-telephone-number.js
src/lib/resource/sections/rep-type.js
src/template.js

- third party reps sections and routes added

Feature/third party/release candidate

---

src/lib/resource/sections/applicant-are-you-18-or-over.js

Change the word "Person" to "Victim" in "Is the person over 18"
Manual test pass
Lint pass

Update age content for reps - CICA-266

---

src/lib/resource/sections/rep-organisation-name.js

Fix bug on master
Manual test pass
Lint pass

Remove incorrect answer from examples

---

src/lib/resource/sections/contact-cica.js
src/lib/resource/sections/new-or-existing-application.js
src/template.js

Add new application start page and new contact CICA page.
Manual test pass
Lint pass
UAT signed off

Add new start page and contact CICA page

---

src/lib/resource/sections/applicant-are-you-18-or-over.js
src/lib/resource/sections/applicant-british-citizen-or-eu-national.js
src/lib/resource/sections/applicant-enter-your-address.js
src/lib/resource/sections/applicant-enter-your-date-of-birth.js
src/lib/resource/sections/confirmation.js
src/lib/resource/sections/context-authority.js
src/lib/resource/sections/context-mainapplicant-details.js
src/lib/resource/sections/flow-has-legal-authority.js
src/lib/resource/sections/mainapplicant-care-order-authority.js
src/lib/resource/sections/mainapplicant-care-order.js
src/lib/resource/sections/mainapplicant-parent.js
src/lib/resource/sections/mainapplicant-relationship.js
src/lib/resource/sections/rep-address.js
src/lib/resource/sections/rep-reference-number.js
src/template.js

Update routing to match Miro
Add confirmation contexts

Rc new routing

---

src/lib/resource/sections/applicant-enter-your-address.js
src/lib/resource/sections/confirmation.js

Fix parsing error in confirmation 
Fix applicant-address routing

Fix parsing error in confirmation && fix applicant-address routing

---

src/lib/resource/sections/applicant-enter-your-telephone-number.js
src/lib/resource/sections/confirmation.js
src/lib/resource/sections/context-authority.js
src/lib/resource/sections/mainapplicant-care-order-authority.js
src/lib/resource/sections/mainapplicant-relationship.js
src/lib/resource/sections/mainapplicant-shared-responsibility.js
src/template.js

- Update Confirmation page(s)
- Correct routing for reps journey
- Update role definitions

Fix the precedence of roles in confirmation

---

package-lock.json
package.json
src/lib/resource/sections/applicant-additional-information.js
src/lib/resource/sections/applicant-affect-on-daily-life-dmi.js
src/lib/resource/sections/applicant-incident-description.js
src/lib/resource/sections/applicant-unable-to-work.js
src/template.js

Increase character limits of text boxes from 1000 to 2000
Fix document number

Character limit increase

---

src/lib/resource/sections/flow-has-legal-authority.js
src/lib/resource/sections/flow-represents-legal-authority.js
src/template.js

Update the type of contextualisation used for the taxonomy section
Update the theme for the legal-authority pages.

Update taxonomy && change themes for legal-auth pages

---

src/lib/resource/sections/applicant-unable-to-work-duration.js
src/lib/resource/sections/applicant-unable-to-work.js
src/lib/resource/sections/applicant-work-details-option.js
src/lib/resource/sections/confirmation.js
src/lib/resource/sections/context-crime-impact.js
src/template.js

Change routing of impact section for third party reps

Change routing of impact section for third party reps

---

package-lock.json
package.json
src/lib/resource/sections/confirmation.js
src/lib/resource/sections/context-authority.js
src/template.js

Update "noAuthority" to "noauthority"
Update document version number
Validates against `taxa-title-expressions` branch of q-template-validator.

Update noauthority role && bump questionnaireDocumentNumber

---

package-lock.json
package.json
src/lib/resource/sections/applicant-affect-on-daily-life-dmi.js

Special expenses are to be asked in every scenario.
Removed the `treatment` routing fork. and it now satisfies the routing described in cica-400.
tested locally.

Remove treatment routing fork

---

src/template.js

* applicant:adult
* mainapplicant.applicant:adult:incapable
* mainapplicant.applicant:child
* rep.applicant:adult:capable
* rep.mainapplicant.applicant:adult:incapable
* rep.mainapplicant.applicant:child
* rep:no-legal-authority.applicant

Add email and sms confirmation actions

---

src/lib/resource/sections/confirmation.js

Add content bug fix for rep adult applicant confirmation page

Add content bug fix for rep adult applicant confirmation page

---

package-lock.json
package.json
src/lib/resource/sections/applicant-when-did-the-crime-happen.js
src/lib/resource/sections/applicant-when-did-the-crime-start.js
src/lib/resource/sections/applicant-when-did-the-crime-stop.js
src/lib/resource/sections/when-was-the-crime-reported-to-police.js

Update date examples

---

src/lib/resource/sections/applicant-relationship-to-deceased.js
src/lib/resource/sections/applicant-you-cannot-get-compensation.js

Routing corrections added for deceased journey:
https://dsdmoj.atlassian.net/jira/software/c/projects/CDS2/boards/994?modal=detail&selectedIssue=CDS2-173
https://dsdmoj.atlassian.net/jira/software/c/projects/CDS2/boards/994?modal=detail&selectedIssue=CDS2-198

Deceased journey refactoring and routing

---

package-lock.json
package.json
src/lib/resource/sections/mainapplicant-shared-responsibility-name.js

- Bump typescript dependancy to 5.0.4
- Add maxLength field to q-mainapplicant-shared-responsibility-name

Bug/cds2 204/add char limit

---

src/lib/resource/sections/context-authority.js
src/lib/resource/sections/mainapplicant-enter-your-name.js
src/lib/resource/sections/mainapplicant-relationship.js
src/lib/resource/sections/mainapplicant-shared-responsibility.js

Various context changes for tickets CDS2-228 to 230 covering:
- rep mainapplicant child 
- rep mainapplicant adult incapable
- rep no-legal-authority adult incapable

Deceased journey cds 228 to 230

---

src/lib/resource/sections/mainapplicant-relationship.js

Correct the error message display for mainapplicant-deceased-child

Fix error message on mainapplicant-relationship

---

src/lib/resource/sections/applicant-applied-for-other-compensation-briefly-explain-why-not.js
src/lib/resource/sections/applicant-has-a-decision-been-made.js
src/lib/resource/sections/applicant-have-you-applied-for-or-received-any-other-compensation.js
src/lib/resource/sections/applicant-how-much-was-award.js
src/lib/resource/sections/applicant-when-will-you-find-out.js
src/lib/resource/sections/applicant-who-did-you-apply-to.js
src/lib/resource/sections/mainapplicant-care-order.js
src/lib/resource/sections/mainapplicant-shared-responsibility-name.js

Added changes for deceased someone else journey other compensation

Added deceased journey other compensation changes

---

src/lib/resource/sections/applicant-when-will-you-find-out.js
src/lib/resource/sections/applicant-who-did-you-apply-to.js

Error message corrections for 
applicant-when-will-you-find-out
applicant-who-did-you-apply-to
Corrected context switching for non fatal someone else journey

Deceased journey other compensation

---

src/lib/resource/sections/applicant-work-details-option.js

Prevent allowing white space as an input on the applicant-work-details-options page

Deceased journey bug 202 fix

---

.huskyrc.js
package-lock.json
package.json

- Update q-template-validator dev dependency version
- Configure husky to automatically run the validation tests on commit

Q template validator update

---

src/lib/resource/sections/applicant-claim-type.js
src/lib/resource/sections/applicant-disabling-mental-injury.js
src/lib/resource/sections/applicant-financial-help.js
src/lib/resource/sections/applicant-funeral-costs-who-contributed.js
src/lib/resource/sections/applicant-immediate-aftermath.js
src/lib/resource/sections/applicant-physical-help.js
src/lib/resource/sections/applicant-relationship-to-deceased.js
src/lib/resource/sections/context-deceased-details.js
src/lib/resource/sections/other-claimants.js

Correct examples and metadata on various pages

Correct examples and meta data

---

src/lib/resource/sections/check-your-answers.js
src/lib/resource/sections/confirmation.js
src/lib/resource/sections/mainapplicant-declaration-12-and-over-deceased.js
src/lib/resource/sections/mainapplicant-declaration-under-12-deceased.js
src/template.js

Deceased journey mainapplicant submissions

Deceased journey mainapplicant submissions

---

src/lib/resource/sections/confirmation.js

Corrected confirmation page  for mainpplicant child deceased

Corrected confirmation page  for mainpplicant child deceased

---

src/lib/resource/sections/applicant-are-you-18-or-over.js
src/lib/resource/sections/applicant-fatal-claim.js
src/lib/resource/sections/applicant-has-crime-reference-number.js
src/lib/resource/sections/applicant-physical-injury-arms.js
src/lib/resource/sections/applicant-physical-injury-legs.js
src/lib/resource/sections/applicant-physical-injury-torso.js
src/lib/resource/sections/applicant-physical-injury-upper.js
src/lib/resource/sections/applicant-who-are-you-applying-for.js
src/lib/resource/sections/new-or-existing-application.js

Adding 
`integration: {
hideOnSummary: true
}
`
to the meta json object for questions which we do not want to appear on the pdf summary

Add hideOnSummary flag to meta 

---

src/lib/resource/sections/system.js

[CDBT-153] Secondary CRN

---

src/lib/resource/sections/check-your-answers.js

Fixed routing to correct deceased declaration for Reps: foster carer, friend or relative with incapable or under 12 claimant

Fixed routing for friend or foster care in deceased routes

---

src/lib/resource/sections/mainapplicant-care-order-authority.js

Corrected routing for rep details

Corrected routing for rep details

---

src/lib/resource/sections/applicant-dentist-address.js
src/lib/resource/sections/applicant-enter-your-address.js
src/lib/resource/sections/applicant-treatment-address.js
src/lib/resource/sections/deceased-address.js
src/lib/resource/sections/gp-enter-your-address.js
src/lib/resource/sections/mainapplicant-enter-your-address.js
src/lib/resource/sections/rep-address.js
src/lib/resource/sections/rep-organisation-address.js

Make postcode mandatory

---

src/lib/resource/sections/context-residency-and-nationality.js

fix residency context page contextualisation

fix residency context page contextualisation

---

src/lib/resource/sections/applicant-relationship-to-deceased.js

Fixed questions for relationship to deceased on Check your answers page

Deceased residency merge cya relationship to deceased

---

src/lib/resource/sections/applicant-relationship-to-deceased.js

Fixed title apostrophe for someone else jurney

Fixed title apostrophe for someone else jurney

---

package-lock.json
package.json
src/lib/resource/sections/applicant-are-you-18-or-over.js
src/lib/resource/sections/confirmation.js
src/template.js

-- update email templates
-- update multiple CRN confirmation
-- add tasks to template
-- update questionnaireDocumentVersion to 5.0.0
-- Bump q-template-validtor to v7.0.0

Cdbt sanity test

---

src/lib/resource/sections/applicant-confirmation-method.js
src/lib/resource/sections/applicant-enter-your-address.js
src/lib/resource/sections/confirmation.js
src/lib/resource/sections/mainapplicant-confirmation-method.js
src/lib/resource/sections/mainapplicant-enter-your-address.js
src/lib/resource/sections/rep-address.js
src/lib/resource/sections/rep-confirmation-method.js
src/lib/resource/sections/rep-organisation-address.js
src/template.js

Main journey no contact method for applicant

Main journey no contact method

---

src/lib/resource/sections/transition-someone-18-or-over-to-apply.js

Link for transition page to go to start or resume corrected

Corrected link

---

package-lock.json
package.json
src/lib/resource/sections/transition-someone-18-or-over-to-apply.js

Removed trailing slash from link

Removed trailing slash from link

---

src/lib/resource/sections/applicant-are-you-18-or-over.js

https://dsdmoj.atlassian.net/jira/software/c/projects/CDBT/boards/1082?modal=detail&selectedIssue=CDBT-300

updating 18-or-over to show on summary

---

src/lib/resource/sections/check-your-answers.js

Added header to CYA page

---

package-lock.json
package.json
src/lib/resource/sections/applicant-crime-location.js

Changed bereavement and non-bereavement  flows on crime location page

Changed bereavement and non-bereavement flow on crime location page

---

package-lock.json
package.json
src/lib/resource/sections/context-compensation.js
src/lib/resource/sections/deceased-address.js

Fixed deceased address and and context compensation content

Fixed deceased address and and context compensation content

---

package-lock.json
package.json
src/lib/resource/sections/applicant-applied-before-for-this-crime.js
src/lib/resource/sections/applicant-fatal-claim.js
src/lib/resource/sections/applicant-have-you-applied-for-or-received-any-other-compensation.js
src/lib/resource/sections/applicant-have-you-applied-to-us-before.js
src/lib/resource/sections/applicant-someone-else-applied-before-for-this-crime.js
src/lib/resource/sections/context-you-should-not-apply-again.js
src/lib/resource/sections/proxy-someone-else-applied-before-for-this-crime.js
src/template.js

Ready for a final check, it has been content checked.
Version patch proposed.

Add previously applied duplicate page tests

---

package-lock.json
package.json
src/lib/resource/sections/applicant-has-a-decision-been-made.js
src/lib/resource/sections/applicant-how-much-was-award.js
src/lib/resource/sections/applicant-special-expenses.js
src/lib/resource/sections/applicant-who-did-you-apply-to.js
src/lib/resource/sections/which-police-force-is-investigating-the-crime.js

Includes ticket CICA-1384 for special expenses content fixes, CICA-1357 for changes to other compensation section content and CICA-1442 for which police force content

Content changes

---

src/lib/resource/sections/applicant-you-cannot-get-compensation.js
src/lib/resource/sections/before-you-continue.js
src/lib/resource/sections/context-additional-info.js
src/lib/resource/sections/context-applicant-details.js
src/lib/resource/sections/context-authority.js
src/lib/resource/sections/context-compensation.js
src/lib/resource/sections/context-crime-impact.js
src/lib/resource/sections/context-crime-ref-no.js
src/lib/resource/sections/context-deceased-details.js
src/lib/resource/sections/context-dmi-details.js
src/lib/resource/sections/context-funeral-costs-proof.js
src/lib/resource/sections/context-funeral-costs.js
src/lib/resource/sections/context-mainapplicant-details.js
src/lib/resource/sections/context-money.js
src/lib/resource/sections/context-offender.js
src/lib/resource/sections/context-physical-injuries.js
src/lib/resource/sections/context-pregnancy.js
src/lib/resource/sections/context-relationship-to-deceased.js
src/lib/resource/sections/context-rep-details.js
src/lib/resource/sections/context-residency-and-nationality.js
src/lib/resource/sections/context-special-expenses.js
src/lib/resource/sections/context-treatment.js

Add pageType meta data to pages that require no input

Add page type meta data to context pages

---

behaviours/tests/features/feature_files/applicant/applicant-adult-sms.feature
package-lock.json
package.json
src/lib/resource/sections/applicant-select-reasons-for-the-delay-in-making-your-application.js
src/lib/resource/sections/applicant-when-did-the-crime-happen.js
src/lib/resource/sections/applicant-when-did-the-crime-stop.js
src/template.js

Update content on and routing to `applicant-select-reasons-for-the-delay-in-making-your-application`
Add a new role for a user who is applying for a crime that happened when they were a child to change content on `applicant-select-reasons-for-the-delay-in-making-your-application`

Update routing to and content of reasons for delay in applying page
